[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=42",
  "setuptools-scm>=7"
]

[project]
authors = [{name = "Taher Chegini", email = "cheginit@gmail.com"}]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "Topic :: Scientific/Engineering :: GIS",
  "Topic :: Scientific/Engineering :: Hydrology",
  "Typing :: Typed"
]
dependencies = [
  "async-retriever>=0.3.10",
  "click>=0.7",
  "dask",
  "geopandas>=0.10",
  "lxml",
  "numpy>=1.21",
  "pandas>=1.0",
  "py3dep>=0.13.10",
  "pygeoogc>=0.13.10",
  "pygeoutils>=0.13.11",
  "pyproj>=2.2",
  "rasterio>=1.2",
  "rioxarray>=0.11.0",
  "scipy",
  "shapely>=1.8",
  "xarray>=2022.03.0"
]
description = "Access daily, monthly, and annual climate data via the Daymet web service."
dynamic = ["version"]
license = {text = "MIT"}
name = "pydaymet"
requires-python = ">=3.8"

[project.optional-dependencies]
speedup = ["numba"]
test = [
  "coverage[toml]",
  "pyarrow>=1.0.1",
  "pytest-cov",
  "pytest-xdist[psutil]"
]
typeguard = [
  "coverage[toml]",
  "pyarrow>=1.0.1",
  "pygments",
  "pytest-cov",
  "pytest-xdist[psutil]",
  "typeguard"
]

[project.readme]
content-type = "text/x-rst"
file = "README.rst"

[project.scripts]
pydaymet = "pydaymet.cli:cli"

[project.urls]
CI = "https://github.com/hyriver/pydaymet/actions"
Changelog = "https://docs.hyriver.io/changelogs/pydaymet.html"
Homepage = "https://docs.hyriver.io/readme/pydaymet.html"
Issues = "https://github.com/hyriver/pydaymet/issues"

[tool.bandit]
targets = [
  "pydaymet"
]

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.codespell]
skip = "__pycache__,_build,.mypy_cache,.git,./htmlcov,.nox"

[tool.coverage.report]
exclude_lines = [
  'raise ServiceUnavailableError',
  "if TYPE_CHECKING:",
]
ignore_errors = true

[tool.coverage.run]
branch = true
parallel = true
source = ['pydaymet']
omit =[
    "**/__init__.py",
    "**/print_versions.py",
]

[tool.isort]
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "pydaymet"
line_length = 100
multi_line_output = 3
profile = "black"
use_parentheses = true

[tool.pycln]
all = true
expand_stars = true
no_gitignore = false
verbose = true

[tool.pyright]
exclude = [
  ".nox/",
  "**/__pycache__",
  "**/__init__.py",
  "tests/"
]
include = ["pydaymet"]
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryIsInstance = false
reportUntypedFunctionDecorator = false
typeCheckingMode = "strict"

[tool.pytest.ini_options]
addopts = "--ignore=noxfile.py -n=auto -v --cov=pydaymet --cov-report xml --durations=5"
doctest_optionflags = 'NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL NUMBER'
filterwarnings = [
  "ignore:.*distutils.*",
  "ignore:.*this is an initial implementation.*",
  "ignore:.*--rsyncdir command line argument.*",
  "ignore:.*numpy.ndarray size changed.*"
]
testpaths = [
  "tests",
  "pydaymet"
]

[tool.refurb]
python_version = "3.8"
quiet = true

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE"]
platforms = ["any"]
zip-safe = false

[tool.setuptools.package-data]
pydaymet = ["py.typed"]

[tool.setuptools.packages]
find = {namespaces = false}

[tool.setuptools_scm]
fallback_version = "999"
