name: pydaymet-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - defusedxml
  - nest-asyncio
  - orjson

  # pygeoogc deps
  - owslib
  - pydantic
  - pyyaml
  - pyproj
  - requests
  - requests-cache
  - shapely
  - simplejson
  - urllib3

  # pygeoutils deps
  - affine
  - dask
  - geopandas
  - netcdf4
  - numpy
  - rasterio
  - xarray

  # py3dep
  - click

  # pydaymet deps
  - lxml
  - scipy

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - nox
  - psutil
  - pytest
  - pytest-clarity
  - pytest-console-scripts
  - pytest-cov
  - pytest-sugar
  - pytest-xdist

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/py3dep.git
