name: pydaymet-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - setuptools

  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - chardet
  - cytoolz
  - nest-asyncio
  - orjson

  # pygeoogc deps
  # - cytoolz
  - defusedxml
  - owslib
  - pyproj
  - requests
  - requests_cache
  - shapely
  - simplejson

  # pygeoutils deps
  - geopandas
  - netcdf4
  - rasterio
  - xarray

  # pydaymet deps
  - dask-core
  - lxml
  - scipy

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - pytest
  - pytest-cov
  - pytest-xdist
  - flaky

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/py3dep.git
